### PR TITLE
Add dd amazon mq

### PR DESCRIPTION
**Pull request by srhopkins**
## what
* Adding baseline Amazon MQ Datadog standard monitors 

## why
* Establish an out of box baseline set of monitors that can be used with Datadog Amazon MQ integration

### CODE REVIEW

**Comment by Gowiem** [comment]
@srhopkins stoked to see this! Quick request: Anyway you can delineate in code or via comments between what monitors will work with AmazonMQ vs RabbitMQ? Will definitely want to use one of these for a client, but I'd only be interested in RMQ monitors. If that is out of scope then that is totally fine as I can circle back at some point if I end up using them.

**Comment by srhopkins** [comment]
@Gowiem I don't see overlapping metrics for RMQ https://docs.datadoghq.com/integrations/rabbitmq/?tab=host#data-collected

**Review by jamengual — APPROVED** [review]

**Pull request merged**
