### PR TITLE
 Fix/feat: Improve Kubernetes Alert Context

### PR DESCRIPTION
**Pull request by korenyoni**
## what
* Improve Kubernetes alert context by aggregating on `cluster_name` or `cluster_name,kube_namespace` where possible
* Add variables made available by these contexts to the alert message, such that alerted platforms can make use of additional data (e.g. OpsGenie)

## why
* Kubernetes alerts with more information i.e. which cluster, namespace are more actionable

## references
* N/A

### CODE REVIEW

**Review by osterman — DISMISSED** [review]

**Review by aknysh — APPROVED** [review]

**Comment by korenyoni** [comment]
Tests failed due to deprecated `datadog_monitor` arguments in the Datadog Terraform Provider: https://github.com/DataDog/terraform-provider-datadog/commit/1b0e69cc0b3aa6834c1bcc974a21e54bae01af9b

Going to merge in #30 first

**Review by htplbc — APPROVED** [review]
thank you

**Pull request merged**
